### ISSUE TITLE
[BUG]: update database action broken by 0.14.0 release

### ISSUE THREAD

**Issue by leecannon** [Zigistry/Zigistry#52]
The [update database action](https://github.com/Zigistry/Zigistry/actions/workflows/main.yaml) is broken by the release of zig 0.14.0.

Going forward it is probably a good idea to specify a zig version in the action to prevent breakages before the code can be updated.

```yaml
  - uses: mlugg/setup-zig@v1
    with:
      version: 0.13.0
```
